#baseUrl
@baseUrl=ws://localhost:3000

# update user
POST {{baseUrl}} {player}
{
    "action":"create",
    "data":{
        "displayName":"MIDLAJ C"
    }
}
{
    "action":"update",
    "data":{
        "displayName":"MIDLAJ C"
    }
}


POST {{baseUrl}} {quick_play}


POST {{baseUrl}} {play_with_friend}
{
    "action":"request",
    "data":{
        "friendUuid":"55xl8gppcz3"
    }
}
{
    "action": "response",
    "data": {
        "response":"accept",
        "opponent": {
            "id": 54,
            "uuid": "55xl8gppcz3",
            "socketId": "z7rPc8hEam16EEHIAAAD",
            "displayName": "MIDLAJ"
        },
        "roomId": "room_55xl8gprwq7"
    }
}